name: 🚀 Deploy backend on push branch main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code on branch main
        uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@v0.1.4

        env:
          HOST: ${{ secrets.HOSTNAME }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        with:
          source: "."
          target: "/var/app7/simakda_2024"

        env:
          HOST: ${{ secrets.HOSTNAME_W }}
          USERNAME: ${{ secrets.USERNAME_W }}
          PORT: ${{ secrets.PORT_W }}
          KEY: ${{ secrets.SSHKEY_W }}
          PASSPHRASE: ${{ secrets.PASSPHRASE_W }}
        with:
          source: "."
          target: "D:/aplikasi/2024/simakda_2024"